---
# Description : inventory_agent_clt_installation installation without docker container
# file : _inventory_agent_clt_raw.yml

## install required packages
- name: Install required packages
  ansible.builtin.include_role:
    name: apt_packages_install
  vars:
    apt_source_package_list: "{{ inventory_agent_clt_packages_requirement_list }}"
    apt_repo_purge: false

## validate repository path
- name: Make sure distant script dir exist
  ansible.builtin.file:
    path: "{{ inventory_agent_clt_local_dir }}"
    state: directory
    mode: '0755'

## git clone inventory_agent_clt
- name: Clone inventory_agent_clt locally
  ansible.builtin.git:
    repo: https://github.com/maraudeurs/srv-inventory_agent_clt.git
    dest: "{{ inventory_agent_clt_local_dir }}"

- name: Make sure that main script is executable
  ansible.builtin.file:
    path: "{{ inventory_agent_clt_python_folder_path }}/main.py"
    owner: "{{ inventory_agent_clt_scripts_user }}"
    group: "{{ inventory_agent_clt_scripts_group }}"
    mode: '0744'

## set venv path
- name: Make sure venv path exist
  ansible.builtin.file:
    path: "{{ inventory_agent_clt_venv_path }}"
    state: directory
    mode: '0744'

- name: Create virtual environment
  command: python3 -m venv {{ inventory_agent_clt_venv_path }}
  args:
    creates: "{{ inventory_agent_clt_venv_path }}/bin/activate"

- name: Install required Python packages
  pip:
    requirements: "{{ inventory_agent_clt_local_dir }}/requirements.txt"
    virtualenv: "{{ inventory_agent_clt_venv_path }}"

## set systemd usage
- name: Send systemctl service config file to srv
  ansible.builtin.template:
    src: inventory_agent_clt.service.j2
    dest: /etc/systemd/system/inventory_agent_clt.service
    owner: "{{ inventory_agent_clt_scripts_user }}"
    group: "{{ inventory_agent_clt_scripts_group }}"
    mode: '0644'
  notify: reload systemctl config

- name: Enable inventory_agent_clt service
  ansible.builtin.systemd_service:
    name: inventory_agent_clt.service
    enabled: true
    masked: no

## start main script
- name: Start inventory_agent_clt service now
  ansible.builtin.systemd_service:
    name: inventory_agent_clt.service
    state: started